//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounsleSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounselRequest
    {
        public int id { get; set; }
        public int studentid { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string isaccept { get; set; }
        public string updatedby { get; set; }
    }
}
